# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1p1', models.CharField(max_length=150)),
                ('d1p2', models.CharField(max_length=150)),
                ('d1p3', models.CharField(max_length=150)),
                ('d1p4', models.CharField(max_length=150)),
                ('d2p1', models.CharField(max_length=150)),
                ('d2p2', models.CharField(max_length=150)),
                ('d2p3', models.CharField(max_length=150)),
                ('d2p4', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default=0, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='organizer.Student'),
        ),
    ]
